#pragma once

#include <cstdint>

namespace GL
{
	/*
	* SDLK_UNKNOWN = 0,

    SDLK_RETURN = '\r',
    SDLK_ESCAPE = '\x1B',
    SDLK_BACKSPACE = '\b',
    SDLK_TAB = '\t',
    SDLK_SPACE = ' ',
    SDLK_EXCLAIM = '!',
    SDLK_QUOTEDBL = '"',
    SDLK_HASH = '#',
    SDLK_PERCENT = '%',
    SDLK_DOLLAR = '$',
    SDLK_AMPERSAND = '&',
    SDLK_QUOTE = '\'',
    SDLK_LEFTPAREN = '(',
    SDLK_RIGHTPAREN = ')',
    SDLK_ASTERISK = '*',
    SDLK_PLUS = '+',
    SDLK_COMMA = ',',
    SDLK_MINUS = '-',
    SDLK_PERIOD = '.',
    SDLK_SLASH = '/',
    SDLK_0 = '0',
    SDLK_1 = '1',
    SDLK_2 = '2',
    SDLK_3 = '3',
    SDLK_4 = '4',
    SDLK_5 = '5',
    SDLK_6 = '6',
    SDLK_7 = '7',
    SDLK_8 = '8',
    SDLK_9 = '9',
    SDLK_COLON = ':',
    SDLK_SEMICOLON = ';',
    SDLK_LESS = '<',
    SDLK_EQUALS = '=',
    SDLK_GREATER = '>',
    SDLK_QUESTION = '?',

    SDLK_LEFTBRACKET = '[',
        SDLK_BACKSLASH = '\\',
        SDLK_RIGHTBRACKET = ']',
        SDLK_CARET = '^',
        SDLK_UNDERSCORE = '_',
        SDLK_BACKQUOTE = '`',
        SDLK_a = 'a',
        SDLK_b = 'b',
        SDLK_c = 'c',
        SDLK_d = 'd',
        SDLK_e = 'e',
        SDLK_f = 'f',
        SDLK_g = 'g',
        SDLK_h = 'h',
        SDLK_i = 'i',
        SDLK_j = 'j',
        SDLK_k = 'k',
        SDLK_l = 'l',
        SDLK_m = 'm',
        SDLK_n = 'n',
        SDLK_o = 'o',
        SDLK_p = 'p',
        SDLK_q = 'q',
        SDLK_r = 'r',
        SDLK_s = 's',
        SDLK_t = 't',
        SDLK_u = 'u',
        SDLK_v = 'v',
        SDLK_w = 'w',
        SDLK_x = 'x',
        SDLK_y = 'y',
        SDLK_z = 'z',

        SDLK_CAPSLOCK = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CAPSLOCK),

        SDLK_F1 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F1),
        SDLK_F2 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F2),
        SDLK_F3 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F3),
        SDLK_F4 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F4),
        SDLK_F5 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F5),
        SDLK_F6 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F6),
        SDLK_F7 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F7),
        SDLK_F8 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F8),
        SDLK_F9 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F9),
        SDLK_F10 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F10),
        SDLK_F11 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F11),
        SDLK_F12 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F12),

        SDLK_NUMLOCKCLEAR = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_NUMLOCKCLEAR),
        SDLK_KP_DIVIDE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DIVIDE),
        SDLK_KP_MULTIPLY = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MULTIPLY),
        SDLK_KP_MINUS = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MINUS),
        SDLK_KP_PLUS = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUS),
        SDLK_KP_ENTER = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_ENTER),
        SDLK_KP_1 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_1),
        SDLK_KP_2 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_2),
        SDLK_KP_3 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_3),
        SDLK_KP_4 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_4),
        SDLK_KP_5 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_5),
        SDLK_KP_6 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_6),
        SDLK_KP_7 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_7),
        SDLK_KP_8 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_8),
        SDLK_KP_9 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_9),
        SDLK_KP_0 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_0),
        SDLK_KP_PERIOD = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERIOD),

        SDLK_LCTRL = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LCTRL),
        SDLK_LSHIFT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LSHIFT),
        SDLK_LALT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LALT),
        SDLK_LGUI = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LGUI),
        SDLK_RCTRL = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RCTRL),
        SDLK_RSHIFT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RSHIFT),
        SDLK_RALT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RALT),
        SDLK_RGUI = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RGUI),
	*/
        
    //Mapeo de SDL

    #define GL_SCANCODE_MASK (1<<30)
    #define GL_SCANCODE_TO_KEYCODE(X)  (X | GL_SCANCODE_MASK)

	enum class TecladoTecla : int32_t
	{
        Enter = '\r',
        Esc = '\x1B',
        Borrar = '\b',
        Tab = '\t',
        Espacio = ' ',
        Exclamacion = '!',
        Comillas = '"',
        Hash = '#',
        Porcentaje = '%',
        Dolar = '$',
        Ampersand = '&',
        ComillaSimple = '\'',
        ParentesisI = '(',
        parentesisD = ')',
        Asterisco = '*',
        Mas = '+',
        Coma = ',',
        Menos = '-',
        Punto = '.',
        Slash = '/',
        Numero_0 = '0',
        Numero_1 = '1',
        Numero_2 = '2',
        Numero_3 = '3',
        Numero_4 = '4',
        Numero_5 = '5',
        Numero_6 = '6',
        Numero_7 = '7',
        Numero_8 = '8',
        Numero_9 = '9',
        DosPuntos = ':',
        PuntoComa = ';',
        Menor = '<',
        Igual = '=',
        Mayor = '>',
        InterrogacionCierre = '?',

        CorcheteI = '[',
        SlashAtras = '\\',
        CrocheteD = ']',
        Caret = '^',
        GuionBajo = '_',
        ComillaAtras = '`',
        Letra_A = 'a',
        Letra_b = 'b',
        Letra_c = 'c',
        Letra_d = 'd',
        Letra_e = 'e',
        Letra_f = 'f',
        Letra_g = 'g',
        Letra_h = 'h',
        Letra_i = 'i',
        Letra_j = 'j',
        Letra_k = 'k',
        Letra_l = 'l',
        Letra_m = 'm',
        Letra_n = 'n',
        Letra_o = 'o',
        Letra_p = 'p',
        Letra_q = 'q',
        Letra_r = 'r',
        Letra_s = 's',
        Letra_t = 't',
        Letra_u = 'u',
        Letra_v = 'v',
        Letra_w = 'w',
        Letra_x = 'x',
        Letra_y = 'y',
        Letra_z = 'z',

        Mayuscula = GL_SCANCODE_TO_KEYCODE(57),

        F1 = GL_SCANCODE_TO_KEYCODE(58),
        F2 = GL_SCANCODE_TO_KEYCODE(59),
        F3 = GL_SCANCODE_TO_KEYCODE(60),
        F4 = GL_SCANCODE_TO_KEYCODE(51),
        F5 = GL_SCANCODE_TO_KEYCODE(52),
        F6 = GL_SCANCODE_TO_KEYCODE(53),
        F7 = GL_SCANCODE_TO_KEYCODE(54),
        F8 = GL_SCANCODE_TO_KEYCODE(55),
        F9 = GL_SCANCODE_TO_KEYCODE(56),
        F10 = GL_SCANCODE_TO_KEYCODE(57),
        F11 = GL_SCANCODE_TO_KEYCODE(58),
        F12 = GL_SCANCODE_TO_KEYCODE(59),

        KP_BloqueoNumeros = GL_SCANCODE_TO_KEYCODE(83),
        KP_Dividir = GL_SCANCODE_TO_KEYCODE(84),
        KP_Multiplicar = GL_SCANCODE_TO_KEYCODE(85),
        KP_Menos = GL_SCANCODE_TO_KEYCODE(86),
        KP_Mas = GL_SCANCODE_TO_KEYCODE(87),
        KP_Enter = GL_SCANCODE_TO_KEYCODE(88),
        KP_1 = GL_SCANCODE_TO_KEYCODE(89),
        KP_2 = GL_SCANCODE_TO_KEYCODE(90),
        KP_3 = GL_SCANCODE_TO_KEYCODE(91),
        KP_4 = GL_SCANCODE_TO_KEYCODE(92),
        KP_5 = GL_SCANCODE_TO_KEYCODE(93),
        KP_6 = GL_SCANCODE_TO_KEYCODE(94),
        KP_7 = GL_SCANCODE_TO_KEYCODE(95),
        KP_8 = GL_SCANCODE_TO_KEYCODE(96),
        KP_9 = GL_SCANCODE_TO_KEYCODE(97),
        KP_0 = GL_SCANCODE_TO_KEYCODE(98),
        KP_Punto = GL_SCANCODE_TO_KEYCODE(99),

        LCTRL = GL_SCANCODE_TO_KEYCODE(224),
        LSHIFT = GL_SCANCODE_TO_KEYCODE(225),
        LALT = GL_SCANCODE_TO_KEYCODE(226),
        LWIN = GL_SCANCODE_TO_KEYCODE(227),
        RCTRL = GL_SCANCODE_TO_KEYCODE(228),
        RSHIFT = GL_SCANCODE_TO_KEYCODE(229),
        RALT = GL_SCANCODE_TO_KEYCODE(230),
        RWIN = GL_SCANCODE_TO_KEYCODE(231),
	};
}
